# Generated by Django 4.2.7 on 2024-03-04 12:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=35)),
                ('dis', tinymce.models.HTMLField()),
            ],
        ),
    ]
