# Generated by Django 4.2.7 on 2024-03-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news',
            new_name='NewsArticle',
        ),
    ]
