# Generated by Django 4.2.7 on 2024-03-06 19:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='headline', unique=True),
        ),
    ]
